version: '3.1'
services:
    local:
        build:
            context: .
            dockerfile: ./docker/local/Dockerfile
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./:/app
        env_file:
            - ./.env
    web:
        build:
            context: .
            dockerfile: ./docker/heroku/Dockerfile
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./:/app
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: meow
        ports:
            - 5432:5432
        volumes:
            - ~/docker/volumes/postgres:/var/lib/postgresql/data
    test:
        build:
            context: .
            dockerfile: ./docker/test/Dockerfile
        volumes:
            - ./:/app
        environment:
            - PORT=${PORT}
            - APP_SECRET=${APP_SECRET}
