version: '3.1'
services:
    web:
        build: ./
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./:/app
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: meow
        ports:
            - 5432:5432
        volumes:
            - ~/docker/volumes/postgres:/var/lib/postgresql/data
